## Day 3  Profile row and column counts per file

In [15]:
## import libraries 
import pandas as pd
import numpy as np

In [9]:
## loaing datasets 
customers = pd.read_csv(r"C:\Users\SVS\Desktop\Product_Adoption_customer_sucess\data\raw\Customers.csv")

operations = pd.read_csv(r"C:\Users\SVS\Desktop\Product_Adoption_customer_sucess\data\raw\product_operations.csv")

## Data Profiling

In [11]:
print(customers.shape)
print(operations.shape)

(5000, 20)
(20000, 51)

In [12]:
customers.head()

,customer_id,customer_code,company_name,industry,company_size,customer_segment,employee_count,annual_revenue_usd,country,region,city,signup_date,first_login_date,last_login_date,login_count,customer_tenure_months,organization_age,account_manager_id,customer_status,customer_type
0,CUST000001,CC000001,Apex Technologies 1,Information Technology,SMB,SMB,213,2000000,India,South Asia,Hyderabad,2024-01-30,2024-02-03,2024-11-09,157,11,16,AM001,Active,B2B
1,CUST000002,CC000002,Vertex Technologies 2,Banking & Finance,SMB,SMB,223,2000000,USA,North America,Boston,2023-03-09,2023-03-09,2023-05-08,238,21,7,AM002,Active,B2B
2,CUST000003,CC000003,Nova Technologies 3,Healthcare,SMB,SMB,204,1000000,UK,Europe,Leeds,2022-07-23,2022-07-29,2023-04-10,618,29,30,AM003,Active,B2B
3,CUST000004,CC000004,BluePeak Technologies 4,Manufacturing,SMB,SMB,51,3000000,Canada,North America,Calgary,2023-03-09,2023-03-14,2024-01-22,235,21,11,AM004,Inactive,B2B
4,CUST000005,CC000005,Quantum Technologies 5,Retail,SMB,SMB,136,2000000,Germany,Europe,Berlin,2023-01-25,2023-01-26,2024-02-27,633,23,24,AM005,Active,B2B

In [13]:
operations.head()

,record_id,customer_id,subscription_id,subscription_plan,plan_category,subscription_start_date,subscription_end_date,billing_cycle,subscription_fee,discount_percent,...,resolution_time_hours,sla_breached,assigned_team,customer_satisfaction,ticket_channel,product_version,release_cycle,churn_risk,monthly_active_user,weekly_active_user
0,REC000001,CUST000001,SUB000001,Growth,Standard,2023-05-18,2023-06-17,Monthly,299,0,...,22,Yes,Support,3.9,Phone,v3.0,LTS,Medium,No,No
1,REC000002,CUST000002,SUB000002,Growth,Standard,2024-03-04,2024-04-03,Quarterly,299,15,...,3,No,Customer Success,3.8,Email,v3.0,Beta,Medium,No,Yes
2,REC000003,CUST000003,SUB000003,Growth,Standard,2023-10-28,2023-11-27,Quarterly,299,5,...,83,No,Customer Success,4.7,Email,v2.0,LTS,Low,Yes,No
3,REC000004,CUST000004,SUB000004,Growth,Standard,2023-02-12,2023-05-13,Quarterly,299,0,...,35,Yes,Billing,4.2,Portal,v2.2,Stable,Low,No,Yes
4,REC000005,CUST000005,SUB000005,Growth,Standard,2024-02-15,2025-02-14,Quarterly,299,5,...,40,Yes,Billing,4.8,Phone,v3.0,Stable,Low,Yes,Yes

In [16]:
## Data Types 
customers.info()
operations.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 20 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   customer_id             5000 non-null   object
 1   customer_code           5000 non-null   object
 2   company_name            5000 non-null   object
 3   industry                5000 non-null   object
 4   company_size            5000 non-null   object
 5   customer_segment        5000 non-null   object
 6   employee_count          5000 non-null   int64
 7   annual_revenue_usd      5000 non-null   int64
 8   country                 5000 non-null   object
 9   region                  5000 non-null   object
 10  city                    5000 non-null   object
 11  signup_date             5000 non-null   object
 12  first_login_date        5000 non-null   object
 13  last_login_date         5000 non-null   object
 14  login_count             5000 non-null   int64
 15  customer_tenure_months  5000 non-null   int64
 16  organization_age        5000 non-null   int64
 17  account_manager_id      5000 non-null   object
 18  customer_status         5000 non-null   object
 19  customer_type           5000 non-null   object
dtypes: int64(5), object(15)
memory usage: 781.4+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 51 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   record_id                 20000 non-null  object
 1   customer_id               20000 non-null  object
 2   subscription_id           20000 non-null  object
 3   subscription_plan         20000 non-null  object
 4   plan_category             20000 non-null  object
 5   subscription_start_date   20000 non-null  object
 6   subscription_end_date     20000 non-null  object
 7   billing_cycle             20000 non-null  object
 8   subscription_fee          20000 non-null  int64
 9   discount_percent          20000 non-null  int64
 10  tax_amount                20000 non-null  float64
 11  final_amount_paid         20000 non-null  float64
 12  payment_status            20000 non-null  object
 13  payment_method            20000 non-null  object
 14  auto_renew                20000 non-null  object
 15  renewal_count             20000 non-null  int64
 16  subscription_status       20000 non-null  object
 17  feature_id                20000 non-null  object
 18  module_name               20000 non-null  object
 19  feature_name              20000 non-null  object
 20  feature_category          20000 non-null  object
 21  first_feature_used        20000 non-null  object
 22  usage_date                20000 non-null  object
 23  usage_count               20000 non-null  int64
 24  active_days               20000 non-null  int64
 25  session_duration_minutes  20000 non-null  int64
 26  average_session_duration  20000 non-null  float64
 27  feature_adoption_rate     20000 non-null  float64
 28  adoption_stage            20000 non-null  object
 29  engagement_score          20000 non-null  int64
 30  feature_success           20000 non-null  object
 31  error_count               20000 non-null  int64
 32  device_type               20000 non-null  object
 33  login_location            20000 non-null  object
 34  ticket_id                 20000 non-null  object
 35  ticket_created_date       20000 non-null  object
 36  first_response_minutes    20000 non-null  int64
 37  ticket_closed_date        20000 non-null  object
 38  issue_category            20000 non-null  object
 39  priority                  20000 non-null  object
 40  ticket_status             20000 non-null  object
 41  resolution_time_hours     20000 non-null  int64
 42  sla_breached              20000 non-null  object
 43  assigned_team             20000 non-null  object
 44  customer_satisfaction     20000 non-null  float64
 45  ticket_channel            20000 non-null  object
 46  product_version           20000 non-null  object
 47  release_cycle             20000 non-null  object
 48  churn_risk                20000 non-null  object
 49  monthly_active_user       20000 non-null  object
 50  weekly_active_user        20000 non-null  object
dtypes: float64(5), int64(10), object(36)
memory usage: 7.8+ MB

In [17]:
## Missing Values 
customers.isnull().sum()
operations.isnull().sum()

record_id                   0
customer_id                 0
subscription_id             0
subscription_plan           0
plan_category               0
subscription_start_date     0
subscription_end_date       0
billing_cycle               0
subscription_fee            0
discount_percent            0
tax_amount                  0
final_amount_paid           0
payment_status              0
payment_method              0
auto_renew                  0
renewal_count               0
subscription_status         0
feature_id                  0
module_name                 0
feature_name                0
feature_category            0
first_feature_used          0
usage_date                  0
usage_count                 0
active_days                 0
session_duration_minutes    0
average_session_duration    0
feature_adoption_rate       0
adoption_stage              0
engagement_score            0
feature_success             0
error_count                 0
device_type                 0
login_location              0
ticket_id                   0
ticket_created_date         0
first_response_minutes      0
ticket_closed_date          0
issue_category              0
priority                    0
ticket_status               0
resolution_time_hours       0
sla_breached                0
assigned_team               0
customer_satisfaction       0
ticket_channel              0
product_version             0
release_cycle               0
churn_risk                  0
monthly_active_user         0
weekly_active_user          0
dtype: int64

In [18]:
(customers.isnull().sum()/len(customers))*100

customer_id               0.0
customer_code             0.0
company_name              0.0
industry                  0.0
company_size              0.0
customer_segment          0.0
employee_count            0.0
annual_revenue_usd        0.0
country                   0.0
region                    0.0
city                      0.0
signup_date               0.0
first_login_date          0.0
last_login_date           0.0
login_count               0.0
customer_tenure_months    0.0
organization_age          0.0
account_manager_id        0.0
customer_status           0.0
customer_type             0.0
dtype: float64

In [19]:
## Duplicates 
customers["customer_id"].duplicated().sum()

np.int64(0)

In [20]:
operations["record_id"].duplicated().sum()

np.int64(0)

In [22]:
customers.nunique()

customer_id               5000
customer_code             5000
company_name              5000
industry                    20
company_size                 4
customer_segment             4
employee_count            1530
annual_revenue_usd         637
country                     10
region                       6
city                        31
signup_date                896
first_login_date           907
last_login_date            940
login_count                880
customer_tenure_months      30
organization_age            34
account_manager_id          60
customer_status              2
customer_type                1
dtype: int64

In [23]:
operations.nunique()

record_id                   20000
customer_id                  5000
subscription_id             20000
subscription_plan               4
plan_category                   2
subscription_start_date       501
subscription_end_date         836
billing_cycle                   3
subscription_fee                4
discount_percent                5
tax_amount                     20
final_amount_paid              20
payment_status                  3
payment_method                  4
auto_renew                      2
renewal_count                   9
subscription_status             1
feature_id                    250
module_name                     8
feature_name                    8
feature_category                3
first_feature_used              8
usage_date                    694
usage_count                   246
active_days                    30
session_duration_minutes      738
average_session_duration     2341
feature_adoption_rate         246
adoption_stage                  3
engagement_score               86
feature_success                 2
error_count                    13
device_type                     3
login_location                  5
ticket_id                   20000
ticket_created_date           787
first_response_minutes        176
ticket_closed_date          11247
issue_category                  5
priority                        4
ticket_status                   4
resolution_time_hours          95
sla_breached                    2
assigned_team                   4
customer_satisfaction          36
ticket_channel                  4
product_version                 4
release_cycle                   3
churn_risk                      3
monthly_active_user             2
weekly_active_user              2
dtype: int64

In [24]:
customers.describe(include="all")
operations.describe(include="all")

,record_id,customer_id,subscription_id,subscription_plan,plan_category,subscription_start_date,subscription_end_date,billing_cycle,subscription_fee,discount_percent,...,resolution_time_hours,sla_breached,assigned_team,customer_satisfaction,ticket_channel,product_version,release_cycle,churn_risk,monthly_active_user,weekly_active_user
count,20000,20000,20000,20000,20000,20000,20000,20000,20000.000000,20000.000000,...,20000.00000,20000,20000,20000.000000,20000,20000,20000,20000,20000,20000
unique,20000,5000,20000,4,2,501,836,3,NaN,NaN,...,NaN,2,4,NaN,4,4,3,3,2,2
top,REC000001,CUST000001,SUB000001,Growth,Standard,2024-03-06,2024-02-04,Quarterly,NaN,NaN,...,NaN,Yes,Engineering,NaN,Portal,v2.2,Beta,Low,Yes,No
freq,1,4,1,10000,12000,57,59,6764,NaN,NaN,...,NaN,10039,5026,NaN,5061,5061,6772,13393,10072,10029
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,734.000000,9.895500,...,48.74610,NaN,NaN,4.196915,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,776.727214,7.050111,...,27.42552,NaN,NaN,0.621857,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99.000000,0.000000,...,2.00000,NaN,NaN,1.100000,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,299.000000,5.000000,...,25.00000,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,299.000000,10.000000,...,49.00000,NaN,NaN,4.300000,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,799.000000,15.000000,...,73.00000,NaN,NaN,4.700000,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2499.000000,20.000000,...,96.00000,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,NaN,NaN