In [21]:
## Import Libraries
import pandas as pd
import numpy as np

In [22]:
customers = pd.read_csv(r"C:\Users\SVS\Desktop\Product_Adoption_customer_sucess\data\raw\Customers.csv")

product = pd.read_csv(r"C:\Users\SVS\Desktop\Product_Adoption_customer_sucess\data\raw\Product_Operations.csv")

In [23]:
customers.head()

,customer_id,customer_code,company_name,industry,company_size,customer_segment,employee_count,annual_revenue_usd,country,region,city,signup_date,first_login_date,last_login_date,login_count,customer_tenure_months,organization_age,account_manager_id,customer_status,customer_type
0,CUST000001,CC000001,Apex Technologies 1,Information Technology,SMB,SMB,213,2000000,India,South Asia,Hyderabad,2024-01-30,2024-02-03,2024-11-09,157,11,16,AM001,Active,B2B
1,CUST000002,CC000002,Vertex Technologies 2,Banking & Finance,SMB,SMB,223,2000000,USA,North America,Boston,2023-03-09,2023-03-09,2023-05-08,238,21,7,AM002,Active,B2B
2,CUST000003,CC000003,Nova Technologies 3,Healthcare,SMB,SMB,204,1000000,UK,Europe,Leeds,2022-07-23,2022-07-29,2023-04-10,618,29,30,AM003,Active,B2B
3,CUST000004,CC000004,BluePeak Technologies 4,Manufacturing,SMB,SMB,51,3000000,Canada,North America,Calgary,2023-03-09,2023-03-14,2024-01-22,235,21,11,AM004,Inactive,B2B
4,CUST000005,CC000005,Quantum Technologies 5,Retail,SMB,SMB,136,2000000,Germany,Europe,Berlin,2023-01-25,2023-01-26,2024-02-27,633,23,24,AM005,Active,B2B

In [24]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 20 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   customer_id             5000 non-null   object
 1   customer_code           5000 non-null   object
 2   company_name            5000 non-null   object
 3   industry                5000 non-null   object
 4   company_size            5000 non-null   object
 5   customer_segment        5000 non-null   object
 6   employee_count          5000 non-null   int64
 7   annual_revenue_usd      5000 non-null   int64
 8   country                 5000 non-null   object
 9   region                  5000 non-null   object
 10  city                    5000 non-null   object
 11  signup_date             5000 non-null   object
 12  first_login_date        5000 non-null   object
 13  last_login_date         5000 non-null   object
 14  login_count             5000 non-null   int64
 15  customer_tenure_months  5000 non-null   int64
 16  organization_age        5000 non-null   int64
 17  account_manager_id      5000 non-null   object
 18  customer_status         5000 non-null   object
 19  customer_type           5000 non-null   object
dtypes: int64(5), object(15)
memory usage: 781.4+ KB

In [5]:
customers.shape

(5000, 20)

In [6]:
product.head()

,record_id,customer_id,subscription_id,subscription_plan,plan_category,subscription_start_date,subscription_end_date,billing_cycle,subscription_fee,discount_percent,...,resolution_time_hours,sla_breached,assigned_team,customer_satisfaction,ticket_channel,product_version,release_cycle,churn_risk,monthly_active_user,weekly_active_user
0,REC000001,CUST000001,SUB000001,Growth,Standard,2023-05-18,2023-06-17,Monthly,299,0,...,22,Yes,Support,3.9,Phone,v3.0,LTS,Medium,No,No
1,REC000002,CUST000002,SUB000002,Growth,Standard,2024-03-04,2024-04-03,Quarterly,299,15,...,3,No,Customer Success,3.8,Email,v3.0,Beta,Medium,No,Yes
2,REC000003,CUST000003,SUB000003,Growth,Standard,2023-10-28,2023-11-27,Quarterly,299,5,...,83,No,Customer Success,4.7,Email,v2.0,LTS,Low,Yes,No
3,REC000004,CUST000004,SUB000004,Growth,Standard,2023-02-12,2023-05-13,Quarterly,299,0,...,35,Yes,Billing,4.2,Portal,v2.2,Stable,Low,No,Yes
4,REC000005,CUST000005,SUB000005,Growth,Standard,2024-02-15,2025-02-14,Quarterly,299,5,...,40,Yes,Billing,4.8,Phone,v3.0,Stable,Low,Yes,Yes

In [7]:
product.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 51 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   record_id                 20000 non-null  object
 1   customer_id               20000 non-null  object
 2   subscription_id           20000 non-null  object
 3   subscription_plan         20000 non-null  object
 4   plan_category             20000 non-null  object
 5   subscription_start_date   20000 non-null  object
 6   subscription_end_date     20000 non-null  object
 7   billing_cycle             20000 non-null  object
 8   subscription_fee          20000 non-null  int64
 9   discount_percent          20000 non-null  int64
 10  tax_amount                20000 non-null  float64
 11  final_amount_paid         20000 non-null  float64
 12  payment_status            20000 non-null  object
 13  payment_method            20000 non-null  object
 14  auto_renew                20000 non-null  object
 15  renewal_count             20000 non-null  int64
 16  subscription_status       20000 non-null  object
 17  feature_id                20000 non-null  object
 18  module_name               20000 non-null  object
 19  feature_name              20000 non-null  object
 20  feature_category          20000 non-null  object
 21  first_feature_used        20000 non-null  object
 22  usage_date                20000 non-null  object
 23  usage_count               20000 non-null  int64
 24  active_days               20000 non-null  int64
 25  session_duration_minutes  20000 non-null  int64
 26  average_session_duration  20000 non-null  float64
 27  feature_adoption_rate     20000 non-null  float64
 28  adoption_stage            20000 non-null  object
 29  engagement_score          20000 non-null  int64
 30  feature_success           20000 non-null  object
 31  error_count               20000 non-null  int64
 32  device_type               20000 non-null  object
 33  login_location            20000 non-null  object
 34  ticket_id                 20000 non-null  object
 35  ticket_created_date       20000 non-null  object
 36  first_response_minutes    20000 non-null  int64
 37  ticket_closed_date        20000 non-null  object
 38  issue_category            20000 non-null  object
 39  priority                  20000 non-null  object
 40  ticket_status             20000 non-null  object
 41  resolution_time_hours     20000 non-null  int64
 42  sla_breached              20000 non-null  object
 43  assigned_team             20000 non-null  object
 44  customer_satisfaction     20000 non-null  float64
 45  ticket_channel            20000 non-null  object
 46  product_version           20000 non-null  object
 47  release_cycle             20000 non-null  object
 48  churn_risk                20000 non-null  object
 49  monthly_active_user       20000 non-null  object
 50  weekly_active_user        20000 non-null  object
dtypes: float64(5), int64(10), object(36)
memory usage: 7.8+ MB

In [8]:
product.shape

(20000, 51)

In [9]:
customers = customers.drop_duplicates()
product = product.drop_duplicates()

In [10]:
customers.columns = customers.columns.str.strip()
product.columns = product.columns.str.strip()

In [11]:
for col in customers.select_dtypes(include="object"):
    customers[col] = customers[col].str.strip()

for col in product.select_dtypes(include="object"):
    product[col] = product[col].str.strip()

In [25]:
## Convert Customer Dte Columns
customer_dates = [
    "signup_date",
    "first_login_date",
    "last_login_date"
]

for col in customer_dates:
    customers[col] = pd.to_datetime(
        customers[col],
        format="%Y-%m-%d",
        errors="coerce"
    )

In [26]:
## convert Product Date columns 
product_dates = [
    "subscription_start_date",
    "subscription_end_date",
    "first_feature_used",
    "usage_date",
    "ticket_created_date",
    "ticket_closed_date"
]

for col in product_dates:
    product[col] = pd.to_datetime(
        product[col],
        format="%Y-%m-%d",
        errors="coerce"
    )

In [27]:
## Fill Missing VAlues 
customers.fillna(customers.median(numeric_only=True), inplace=True)
customers.fillna("Unknown", inplace=True)

In [28]:
product.fillna(product.median(numeric_only=True), inplace=True)
product.fillna("Unknown", inplace=True)

C:\Users\SVS\AppData\Local\Temp\ipykernel_2904\3321210918.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Unknown' has dtype incompatible with datetime64[ns], please explicitly cast to a compatible dtype first.
  product.fillna("Unknown", inplace=True)

In [29]:
print("Customer Dataset Shape :", customers.shape)
print("Product Dataset Shape :", product.shape)

Customer Dataset Shape : (5000, 20)
Product Dataset Shape : (20000, 51)

In [31]:
customers.to_csv(
    r"C:\Users\SVS\Desktop\Product_Adoption_customer_sucess\data\processed\customer_profile_processed.csv",
    index=False
)

product.to_csv(
    r"C:\Users\SVS\Desktop\Product_Adoption_customer_sucess\data\processed\product_operations_processed.csv",
    index=False
)

In [32]:
print("Cleaning Completed Successfully!")
print("Customer Rows :", customers.shape[0])
print("Product Rows :", product.shape[0])
print("Customer Null Values :", customers.isnull().sum().sum())
print("Product Null Values :", product.isnull().sum().sum())

Cleaning Completed Successfully!
Customer Rows : 5000
Product Rows : 20000
Customer Null Values : 0
Product Null Values : 0